[pytest]
# Allows `pytest` to be run from the parent folder after the project was moved
# into the "Capstone Project" directory.
addopts = -v --html="Capstone Project/reports/execution_report.html" --self-contained-html
testpaths = "Capstone Project/tests"
pythonpath = "Capstone Project"
cache_dir = Capstone Project/.pytest_cache
markers =
    e2e: browser-based end-to-end tests
